# docker-compose.base.yml
services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webhook_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d webhook_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  whatsapp:
    image: aldinokemal2104/go-whatsapp-web-multidevice:v5.2.0
    container_name: whatsapp
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - whatsapp:/app/storages
    environment:
      - APP_PORT=3000
      - APP_DEBUG=true
      - APP_OS=Chrome
      - DB_URI=postgres://user:password@postgres:5432/webhook_db?sslmode=disable
      - APP_BASIC_AUTH=admin:admin
      - WHATSAPP_CHAT_STORAGE=false
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d webhook_db" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  whatsapp:
    name: whatsapp
  postgres_data:
    name: postgres_data