# docker-cloud.yml
services:
  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-webhook_db}

  whatsapp:
    extends:
      file: docker-compose.base.yml
      service: whatsapp
    environment:
      - WHATSAPP_WEBHOOK=https://your-domain.com/webhook
      - APP_BASIC_AUTH=${WHATSAPP_AUTH_USER}:${WHATSAPP_AUTH_PASSWORD}

  web-server:
    build: .
    ports:
      - "80:5001"
    depends_on:
      - postgres
      - whatsapp
    environment:
      - DB_URI=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - WHATSAPP_HOST=http://whatsapp:3000
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - VOYAGE_API_KEY=${VOYAGE_API_KEY}
      - LOGFIRE_TOKEN=${LOGFIRE_TOKEN}
      - WHATSAPP_BASIC_AUTH_USER=${WHATSAPP_AUTH_USER}
      - WHATSAPP_BASIC_AUTH_PASSWORD=${WHATSAPP_AUTH_PASSWORD}

volumes:
  wa_llm_whatsapp:
    name: wa_llm_whatsapp
  wa_llm_postgres:
    name: wa_llm_postgres