import sqlmodel

"""add enable_web_search to group

Revision ID: 40dd46ae8e2f
Revises: fix_timezone_columns
Create Date: 2025-12-26 16:33:19.292241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40dd46ae8e2f'
down_revision: Union[str, None] = 'fix_timezone_columns'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('enable_web_search', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'enable_web_search')
    # ### end Alembic commands ###
