import sqlmodel

"""add_auto_summary_fields

Revision ID: e15ea65a6a8f
Revises: c3d4e5f6g7h8
Create Date: 2025-12-22 19:56:04.314632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'e15ea65a6a8f'
down_revision: Union[str, None] = 'c3d4e5f6g7h8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('auto_summary_threshold', sa.Integer(), nullable=True))
    op.add_column('group', sa.Column('msg_count_since_last_summary', sa.Integer(), nullable=False, server_default="0"))
    op.alter_column('group', 'group_topic',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_index('ix_kb_topic_message_kb_topic_id', table_name='kb_topic_message')
    op.drop_index('ix_kb_topic_message_message_id', table_name='kb_topic_message')
    op.alter_column('kbtopic', 'speakers',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('kbtopic', 'subject',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('kbtopic', 'summary',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('kbtopic', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               nullable=True)
    op.alter_column('message', 'text',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('message', 'chat_jid',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('message', 'sender_jid',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index('idx_message_group_jid', table_name='message')
    op.drop_index('idx_message_timestamp', table_name='message')
    op.drop_index('ix_message_text_tsv', table_name='message', postgresql_using='gin')
    op.create_foreign_key(None, 'message', 'sender', ['sender_jid'], ['jid'])
    op.drop_index('idx_reaction_message_id', table_name='reaction')
    op.drop_index('idx_reaction_sender_jid', table_name='reaction')
    op.drop_index('idx_reaction_unique_message_sender', table_name='reaction')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_reaction_unique_message_sender', 'reaction', ['message_id', 'sender_jid'], unique=True)
    op.create_index('idx_reaction_sender_jid', 'reaction', ['sender_jid'], unique=False)
    op.create_index('idx_reaction_message_id', 'reaction', ['message_id'], unique=False)
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_index('ix_message_text_tsv', 'message', [sa.literal_column("to_tsvector('simple'::regconfig, COALESCE(text, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index('idx_message_timestamp', 'message', ['timestamp'], unique=False)
    op.create_index('idx_message_group_jid', 'message', ['group_jid'], unique=False)
    op.alter_column('message', 'sender_jid',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('message', 'chat_jid',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('message', 'text',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('kbtopic', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               nullable=False)
    op.alter_column('kbtopic', 'summary',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('kbtopic', 'subject',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('kbtopic', 'speakers',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index('ix_kb_topic_message_message_id', 'kb_topic_message', ['message_id'], unique=False)
    op.create_index('ix_kb_topic_message_kb_topic_id', 'kb_topic_message', ['kb_topic_id'], unique=False)
    op.alter_column('group', 'group_topic',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('group', 'msg_count_since_last_summary')
    op.drop_column('group', 'auto_summary_threshold')
    # ### end Alembic commands ###
